// Build trình soạn BlockSpace TỪ MÃ NGUỒN scratch-editor (AGPL-3.0) + bản vá của CodeSpace (T11.0).
// SPDX-License-Identifier: AGPL-3.0-only
//
// 1. Clone scratchfoundation/scratch-editor đúng tag + kiểm commit (cache ở .cache/scratch-editor).
// 2. Đưa cây về đúng bản gốc rồi áp editor/patches/*.patch (thứ tự tên file).
// 3. Sinh asset Rex (src/lib/blockspace/) + lọc thư viện: bỏ nhân vật thương hiệu Scratch, thêm Rex.
// 4. npm ci (bỏ lifecycle script: `canvas` native chỉ dùng cho test) + bước prepare của scratch-gui.
// 5. Build các package scratch-gui cần rồi bản standalone với publicPath /studio/editor/.
// 6. Đóng gói file runtime → .cache/blockspace-editor-<ver>.tgz (build.mjs dùng tarball này).
//
// Chạy: `pnpm --filter @lms/studio build:editor` (~10–20 phút lần đầu, cần mạng + ~3 GB đĩa).
import { createHash } from 'node:crypto';
import { execFileSync, spawnSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

import { EDITOR, REX_POSES, DEFAULT_REX_POSES, PUBLIC_PATH, TRADEMARKED_SPRITES } from './editor-config.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CACHE = join(ROOT, '.cache');
// BLOCKSPACE_EDITOR_SRC: dùng một checkout có sẵn (đã cài node_modules) thay vì .cache/scratch-editor.
const SRC = process.env.BLOCKSPACE_EDITOR_SRC || join(CACHE, 'scratch-editor');
const GUI = join(SRC, 'packages', 'scratch-gui');
const PATCHES = join(ROOT, 'editor', 'patches');

// Thứ tự build: phụ thuộc trước (scratch-gui nạp các package này qua `dist/` của workspace).
const DEP_PACKAGES = [
  'task-herder',
  'scratch-storage',
  'scratch-svg-renderer',
  'scratch-render',
  'scratch-paint',
  'scratch-vm',
];

function run(cmd, args, opts = {}) {
  console.log(`[editor] $ ${cmd} ${args.join(' ')}${opts.cwd ? `  (${relative(ROOT, opts.cwd) || '.'})` : ''}`);
  // shell: npm/npx là .cmd trên Windows.
  const r = spawnSync(cmd, args, { stdio: 'inherit', shell: process.platform === 'win32', ...opts });
  if (r.status !== 0) throw new Error(`${cmd} ${args.join(' ')} lỗi (exit ${r.status})`);
}

function git(args, opts = {}) {
  return (execFileSync('git', args, { cwd: SRC, encoding: 'utf8', ...opts }) ?? '').trim();
}

function checkout() {
  if (!existsSync(join(SRC, '.git'))) {
    mkdirSync(CACHE, { recursive: true });
    run('git', ['clone', '--depth', '1', '--branch', EDITOR.tag, EDITOR.repo, SRC]);
  }
  const head = git(['rev-parse', 'HEAD']);
  if (head !== EDITOR.commit) {
    throw new Error(
      `scratch-editor ${EDITOR.tag} trỏ tới ${head}, cần ${EDITOR.commit} — tag bị đổi? Xóa .cache/scratch-editor nếu chủ động nâng bản.`,
    );
  }
  // Về đúng bản gốc (giữ node_modules để lần sau khỏi cài lại), rồi áp bản vá.
  git(['reset', '--hard', '--quiet']);
  git(['clean', '-fdxq', '-e', 'node_modules', '-e', '/.install-stamp']);
  const patches = readdirSync(PATCHES)
    .filter((f) => f.endsWith('.patch'))
    .sort();
  for (const p of patches) {
    console.log(`[editor] áp ${p}`);
    git(['apply', '--whitespace=nowarn', join(PATCHES, p)], { stdio: 'inherit' });
  }
  return patches.length;
}

// --- Rex: asset trong bundle + thư viện nhân vật ---

function pngSize(buf) {
  return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20) };
}

function rexCostumes() {
  return REX_POSES.map((pose) => {
    const data = readFileSync(join(ROOT, 'assets', 'rex', pose.file));
    const md5 = createHash('md5').update(data).digest('hex');
    const { w, h } = pngSize(data);
    return {
      ...pose,
      data,
      json: {
        name: pose.name,
        assetId: md5,
        md5ext: `${md5}.png`,
        dataFormat: 'png',
        // Ảnh cao 200 px, độ phân giải 2 → cao ~100 đơn vị sân khấu, cỡ Mèo của bản gốc.
        bitmapResolution: 2,
        rotationCenterX: Math.round(w / 2),
        rotationCenterY: Math.round(h / 2),
      },
    };
  });
}

function writeRexModule(costumes) {
  const dir = join(GUI, 'src', 'lib', 'blockspace');
  mkdirSync(dir, { recursive: true });
  const lines = [
    '// GENERATED by CodeSpace LMS apps/studio/scripts/build-editor.mjs from apps/studio/assets/rex/.',
    '// Do not edit. SPDX-License-Identifier: AGPL-3.0-only',
  ];
  costumes.forEach((c, i) => {
    writeFileSync(join(dir, c.json.md5ext), c.data);
    // arraybuffer: nạp sẵn vào bộ nhớ của scratch-storage; URL: ảnh xem trước trong thư viện.
    lines.push(`import data${i} from '!arraybuffer-loader!./${c.json.md5ext}?';`);
    lines.push(`import url${i} from './${c.json.md5ext}';`);
  });
  lines.push('', 'export const REX_LIBRARY_COSTUMES = [');
  costumes.forEach((c, i) => lines.push(`    {...${JSON.stringify(c.json)}, data: data${i}, url: url${i}},`));
  lines.push('];', '');
  // Dự án mới: nhân vật Rex với 2 costume (ADR 003 D2), tên "Rex 1", "Rex 2".
  const defaults = DEFAULT_REX_POSES.map((file, i) => {
    const idx = costumes.findIndex((c) => c.file === file);
    if (idx < 0) throw new Error(`DEFAULT_REX_POSES: không có ${file}`);
    return `{...REX_LIBRARY_COSTUMES[${idx}], name: 'Rex ${i + 1}'}`;
  });
  lines.push(`export const DEFAULT_REX_COSTUMES = [${defaults.join(', ')}];`, '');
  writeFileSync(join(dir, 'rex-assets.js'), lines.join('\n'));
}

function rewriteLibraries(costumes) {
  const libDir = join(GUI, 'src', 'lib', 'libraries');
  const read = (f) => JSON.parse(readFileSync(join(libDir, f), 'utf8'));
  const write = (f, v) => writeFileSync(join(libDir, f), JSON.stringify(v, null, 4) + '\n');

  // Tên + hình Mèo Scratch, Gobo, Pico, Nano, Tera, Giga là thương hiệu của Scratch (file TRADEMARK)
  // → gỡ khỏi thư viện nhân vật, và gỡ các costume của chúng khỏi thư viện costume.
  const sprites = read('sprites.json');
  const removed = sprites.filter((s) => TRADEMARKED_SPRITES.includes(s.name));
  if (removed.length !== TRADEMARKED_SPRITES.length) {
    const missing = TRADEMARKED_SPRITES.filter((n) => !removed.some((s) => s.name === n));
    throw new Error(`Thư viện nhân vật đổi? Không thấy: ${missing.join(', ')}`);
  }
  const removedAssets = new Set(removed.flatMap((s) => s.costumes.map((c) => c.assetId)));
  const tags = ['animals', 'fantasy', 'rex', 'codespace'];
  const rexSprites = costumes.map((c) => ({
    name: c.name,
    tags,
    isStage: false,
    costumes: [{ ...c.json, tags }],
    sounds: [],
    variables: {},
    blocks: {},
  }));
  write('sprites.json', [...rexSprites, ...sprites.filter((s) => !removed.includes(s))]);

  const lib = read('costumes.json');
  const kept = lib.filter((c) => !removedAssets.has(c.assetId));
  write('costumes.json', [...costumes.map((c) => ({ ...c.json, tags })), ...kept]);
  console.log(
    `[editor] thư viện: -${removed.length} nhân vật, -${lib.length - kept.length} costume thương hiệu Scratch; +${costumes.length} Rex`,
  );
}

// --- cài + build ---

function install() {
  const lock = createHash('sha256')
    .update(readFileSync(join(SRC, 'package-lock.json')))
    .digest('hex');
  const stamp = join(SRC, '.install-stamp');
  if (!existsSync(stamp) || readFileSync(stamp, 'utf8') !== lock || !existsSync(join(SRC, 'node_modules'))) {
    run('npm', ['ci', '--ignore-scripts', '--no-audit', '--no-fund'], { cwd: SRC });
    writeFileSync(stamp, lock);
  }
  // Sinh src/generated/ (file micro:bit) — `git clean` ở bước checkout đã xóa nên chạy mỗi lần.
  run('node', ['scripts/prepare.mjs'], { cwd: GUI });
}

function build() {
  const env = { ...process.env, NODE_ENV: 'production', CI: 'true', BLOCKSPACE_PUBLIC_PATH: PUBLIC_PATH };
  for (const pkg of DEP_PACKAGES) {
    const dir = join(SRC, 'packages', pkg);
    const { scripts = {} } = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
    // Bỏ phần sinh tài liệu (jsdoc) trong script build của vm/render — không cần cho bundle.
    if (pkg === 'scratch-vm' || pkg === 'scratch-render') run('npx', ['webpack'], { cwd: dir, env });
    else if (scripts.build) run('npm', ['run', 'build'], { cwd: dir, env });
  }
  rmSync(join(GUI, 'dist'), { recursive: true, force: true });
  run('npx', ['webpack'], { cwd: GUI, env: { ...env, BUILD_TYPE: 'dist-standalone' } });
}

/** File runtime của dist/ (bỏ .map, types). */
function pack() {
  const dist = join(GUI, 'dist');
  const out = join(CACHE, 'editor-dist');
  rmSync(out, { recursive: true, force: true });
  let bytes = 0;
  let files = 0;
  const walk = (dir) => {
    for (const name of readdirSync(dir)) {
      const abs = join(dir, name);
      const rel = relative(dist, abs).replaceAll('\\', '/');
      if (statSync(abs).isDirectory()) {
        if (rel !== 'types') walk(abs);
      } else if (!rel.endsWith('.map') && !rel.endsWith('.LICENSE.txt')) {
        mkdirSync(dirname(join(out, rel)), { recursive: true });
        cpSync(abs, join(out, rel));
        bytes += statSync(abs).size;
        files += 1;
      }
    }
  };
  walk(dist);
  // Tên bundle có hash và nằm trong static/ → Caddy cache vĩnh viễn (luật /studio/editor/static/*).
  const jsDir = join(out, 'static', 'js');
  const main = existsSync(jsDir)
    ? readdirSync(jsDir).filter((f) => /^scratch-gui-standalone\.[0-9a-f]+\.js$/.test(f))
    : [];
  if (main.length !== 1)
    throw new Error(`Cần đúng 1 bundle static/js/scratch-gui-standalone.<hash>.js, thấy ${main.length}`);
  writeFileSync(join(out, 'editor.json'), JSON.stringify({ ...EDITOR, entry: `static/js/${main[0]}` }, null, 2) + '\n');

  const tgz = `blockspace-editor-${EDITOR.version}.tgz`;
  // Đường dẫn tương đối + cwd: GNU tar (Git Bash) hiểu "D:\..." là máy chủ "D".
  execFileSync('tar', ['-czf', tgz, '-C', 'editor-dist', '.'], { cwd: CACHE, stdio: 'inherit' });
  const digest =
    'sha512-' +
    createHash('sha512')
      .update(readFileSync(join(CACHE, tgz)))
      .digest('base64');
  return { files, bytes, tgz, digest };
}

const started = Date.now();
const patches = checkout();
const costumes = rexCostumes();
writeRexModule(costumes);
rewriteLibraries(costumes);
install();
build();
const r = pack();
console.log(
  `[editor] scratch-editor ${EDITOR.tag} + ${patches} bản vá: ${r.files} file, ${(r.bytes / 1e6).toFixed(1)} MB → .cache/${r.tgz}`,
);
console.log(`[editor] ${r.digest}`);
console.log(`[editor] xong sau ${((Date.now() - started) / 60000).toFixed(1)} phút`);
